services:
  redis:
    container_name: app-redis
    image: redis:8.0-rc1
    command: redis-server --requirepass 1234 --bind 0.0.0.0
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - app-network
        
  rankcalculator:
    image: rankcalculator
    deploy:
      replicas: 2
    build:
      context: .
      dockerfile: RankCalculator/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  webapp1:
    container_name: webapp1
    volumes:
      - redis_data:/root/.aspnet/DataProtection-Keys
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1234
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
    depends_on:
      - redis

  webapp2:
    container_name: webapp2
    volumes:
      - redis_data:/root/.aspnet/DataProtection-Keys
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1234
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
    depends_on:
      - redis
        
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: app-nginx
    image: nginx:latest
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app-network
    depends_on:
      - webapp1
      - webapp2

volumes:
  redis_data:
  rabbitmq_data:

networks:
  app-network:
